---
title: "Árvores de Vitória - Beta"
author: ""
date: ""
output: flexdashboard::flex_dashboard
self_contained: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r  include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(leaflet)
library(leaflet.extras)
library(rgdal)
library(sf)
library(leafgl)
```

```{r  include=FALSE, message=FALSE, warning=FALSE}
Arvores<-rgdal::readOGR(
	dsn = getwd(), 
			layer = "arvores")
```

```{r  include=FALSE, message=FALSE, warning=FALSE}
#Convert SIRGAS para WGS
Arvores<-spTransform(Arvores,CRS("+proj=longlat"))
```


```{r  include=FALSE, message=FALSE, warning=FALSE}
centroids<-rgeos::gCentroid(Arvores,byid=TRUE)

Arvores<-cbind(Arvores@data,centroids)
```

```{r eval=FALSE, include=FALSE} 
#O código não funciona muito bem, usar framework do pacote leafgl
map<-leaflet(Arvores)%>%
   addMiniMap()%>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
addMarkers(lng = ~x, lat = ~y,
                        popup = ~paste0(
	"<br/><strong>ID:</strong>:",OBJECTID,
	"<br/><strong>Nome popular:</strong>",nomePopula,
	"<br/><strong>Nome científico:</strong>",nomeCienti,
	"<br/><strong>Localidade:</strong>",logradouro),
  clusterOptions = markerClusterOptions())
  
  

map <- addControlGPS(map, options = gpsOptions(position = "topleft", activate = TRUE, 
                                               autoCenter = TRUE, maxZoom = 25, 
                                               setView = FALSE))
activateGPS(map)

```


# Árvores de Vitória


### {.mobile}

```{r echo=FALSE, message=FALSE, warning=FALSE}
#O pacote leafgl tem uma performance melhor porém não permite popup com multiplas linhas. 
#Não consegui fazer gambiarra pra isso


Arvores<-Arvores%>%st_as_sf(.,coords = c("x", "y"))

Arvores$popup<-paste0(Arvores$nomePopula,";",Arvores$nomeCienti)



map<-leaflet(Arvores,width="100%")%>%
   addMiniMap()%>%
    addProviderTiles(providers$CartoDB.Positron,options = tileOptions(maxZoom = 50))%>%
    addTiles(options = tileOptions(maxZoom = 50)) %>%  # Add default OpenStreetMap map tiles
addGlPoints(data=Arvores,lng = ~x, lat = ~y,popup="popup",fillColor ="blueviolet",fillOpacity = 1)


map <- addControlGPS(map, options = gpsOptions(position = "topleft", activate = TRUE, 
                                               autoCenter = TRUE, 
                                               setView = FALSE))
activateGPS(map)

```



### {.no-mobile}

```{r echo=FALSE, message=FALSE, warning=FALSE}
#O pacote leafgl tem uma performance melhor porém não permite popup com multiplas linhas. 
#Não consegui fazer gambiarra pra isso


Arvores<-Arvores%>%st_as_sf(.,coords = c("x", "y"))

Arvores$popup<-paste0(Arvores$nomePopula,";",Arvores$nomeCienti)


map<-leaflet(Arvores,width="100%")%>%
   addMiniMap()%>%
    addProviderTiles(providers$CartoDB.Positron,options = tileOptions(maxZoom = 50))%>%
    addTiles(options = tileOptions(maxZoom = 50)) %>%  # Add default OpenStreetMap map tiles
addGlPoints(data=Arvores,lng = ~x, lat = ~y,popup="popup",fillColor ="blueviolet",fillOpacity = 1)


map <- addControlGPS(map, options = gpsOptions(position = "topleft", activate = TRUE, 
                                               autoCenter = TRUE, 
                                               setView = FALSE))
activateGPS(map)

```

# Sobre

Seja bem vindo ao aplicativo Árvores de Vitória! Qualquer dúvida favor entrar em contato com o desenvolvedor por [email](mailto:ssantos.gabriel@gmail.com). Caso queira saber sobre mais sobre outros projetos do mesmo desenvolvedor visite a página pessoal [Gabriel Santos](https://ecosantos.netlify.app/)

